/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CardLayoutDemo;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.plaf.metal.MetalToggleButtonUI;

/**
 *
 * @author kgmontecinos92
 */
public class MainFrame extends javax.swing.JFrame {
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        Image img = new ImageIcon(getClass().getResource("/CardLayoutDemo/images/avatar.jpg")).getImage();
        //Image newimg = img.getScaledInstance((row1Movies.getWidth()/3)-14,jToggleButton1.getHeight()-titlePanel.getHeight()-14,  java.awt.Image.SCALE_SMOOTH ) ;  
        ImageIcon iconResized = new ImageIcon(img.getScaledInstance((row1Movies.getWidth()/3)-14,jToggleButton1.getHeight()-titlePanel.getHeight()-14,  java.awt.Image.SCALE_SMOOTH ) );
        jToggleButton2.setIcon(iconResized);
        //jToggleButton2.setHorizontalAlignment(SwingConstants.CENTER);
        
        

        //Image a = new ImageIcon(getClass().getResource("/CardLayoutDemo/images/avatar-creative-movie-posters.jpg")).getImage();
        
    }
   
    
    
    private Image scaledImage(Image img, int width, int height){
        
        BufferedImage resizedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = resizedImage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(img,0,0,width,height, null);
        g2.dispose();
        return resizedImage;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayPanel = new javax.swing.JPanel();
        chooseAMoviePanel = new CardLayoutDemo.FirstPanel();
        titlePanel = new javax.swing.JPanel();
        chooseAmovieLabel = new javax.swing.JLabel();
        moviesDisplayPanel = new javax.swing.JPanel();
        row1Movies = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        row2Movies = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        row3Movies = new javax.swing.JPanel();
        row4Movies = new javax.swing.JPanel();
        row5Movies = new javax.swing.JPanel();
        camNavButtonPanel = new javax.swing.JPanel();
        cancelAndLogOffButton = new javax.swing.JButton();
        upButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        chooseTimeAndTickets = new CardLayoutDemo.SecondPanel();
        titlePanel1 = new javax.swing.JPanel();
        chooseAmovieLabel1 = new javax.swing.JLabel();
        chooseTTdisplayPanel = new javax.swing.JPanel();
        selectedMoviePanel = new javax.swing.JPanel();
        chooseTimeAnd3DPanel = new javax.swing.JPanel();
        twoDor3DPanel = new javax.swing.JPanel();
        timeDisplayPanel = new javax.swing.JPanel();
        chooseTicketQty = new javax.swing.JPanel();
        camNavButtonPanel2 = new javax.swing.JPanel();
        upDownButtonsPanel4 = new javax.swing.JPanel();
        card1Button3 = new javax.swing.JButton();
        card2Button3 = new javax.swing.JButton();
        upDownButtonsPanel5 = new javax.swing.JPanel();
        spaceHolder2 = new javax.swing.JButton();
        cancelAndLogOffButton2 = new javax.swing.JButton();
        cancelNextButtonsPanel2 = new javax.swing.JPanel();
        goBackButton2 = new javax.swing.JButton();
        nextButton2 = new javax.swing.JButton();
        chooseSeatsAndCompleteOrder = new javax.swing.JPanel();
        titlePanel2 = new javax.swing.JPanel();
        chooseAmovieLabel2 = new javax.swing.JLabel();
        csacoDisplayPanel = new javax.swing.JPanel();
        chooseSeats = new javax.swing.JPanel();
        transactionDetailsPanel = new javax.swing.JPanel();
        csacoNavButtonPanel1 = new javax.swing.JPanel();
        upDownButtonsPanel2 = new javax.swing.JPanel();
        card1Button2 = new javax.swing.JButton();
        card2Button2 = new javax.swing.JButton();
        upDownButtonsPanel3 = new javax.swing.JPanel();
        spaceHolder1 = new javax.swing.JButton();
        cancelAndLogOffButton1 = new javax.swing.JButton();
        cancelNextButtonsPanel1 = new javax.swing.JPanel();
        goBackButton1 = new javax.swing.JButton();
        nextButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new ScreenWidth().getScreenWidth());

        displayPanel.setLayout(new java.awt.CardLayout());

        chooseAMoviePanel.setLayout(new java.awt.BorderLayout());

        titlePanel.setBackground(new java.awt.Color(102, 255, 102));
        titlePanel.setPreferredSize(new java.awt.Dimension(399, 75));
        titlePanel.setRequestFocusEnabled(false);
        titlePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        chooseAmovieLabel.setText("choose a movie");
        titlePanel.add(chooseAmovieLabel);

        chooseAMoviePanel.add(titlePanel, java.awt.BorderLayout.NORTH);

        moviesDisplayPanel.setLayout(new java.awt.CardLayout());

        row1Movies.setLayout(new java.awt.GridLayout(1, 3));

        jToggleButton1.setText("j1togglebutton");
        row1Movies.add(jToggleButton1);
        row1Movies.add(jToggleButton2);

        jToggleButton3.setText("jToggleButton1");
        row1Movies.add(jToggleButton3);

        moviesDisplayPanel.add(row1Movies, "card1");

        row2Movies.setLayout(new java.awt.GridLayout(2, 2));

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        row2Movies.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        row2Movies.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        row2Movies.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        row2Movies.add(jPanel7);

        moviesDisplayPanel.add(row2Movies, "card2");

        javax.swing.GroupLayout row3MoviesLayout = new javax.swing.GroupLayout(row3Movies);
        row3Movies.setLayout(row3MoviesLayout);
        row3MoviesLayout.setHorizontalGroup(
            row3MoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2016, Short.MAX_VALUE)
        );
        row3MoviesLayout.setVerticalGroup(
            row3MoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );

        moviesDisplayPanel.add(row3Movies, "card3");

        javax.swing.GroupLayout row4MoviesLayout = new javax.swing.GroupLayout(row4Movies);
        row4Movies.setLayout(row4MoviesLayout);
        row4MoviesLayout.setHorizontalGroup(
            row4MoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2016, Short.MAX_VALUE)
        );
        row4MoviesLayout.setVerticalGroup(
            row4MoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );

        moviesDisplayPanel.add(row4Movies, "card4");

        javax.swing.GroupLayout row5MoviesLayout = new javax.swing.GroupLayout(row5Movies);
        row5Movies.setLayout(row5MoviesLayout);
        row5MoviesLayout.setHorizontalGroup(
            row5MoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2016, Short.MAX_VALUE)
        );
        row5MoviesLayout.setVerticalGroup(
            row5MoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );

        moviesDisplayPanel.add(row5Movies, "card5");

        chooseAMoviePanel.add(moviesDisplayPanel, java.awt.BorderLayout.CENTER);

        camNavButtonPanel.setPreferredSize(new java.awt.Dimension(399, 100));
        camNavButtonPanel.setRequestFocusEnabled(false);
        camNavButtonPanel.setLayout(new java.awt.GridLayout(1, 4));

        cancelAndLogOffButton.setText("CANCEL&LOG OUT");
        cancelAndLogOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAndLogOffButtonActionPerformed(evt);
            }
        });
        camNavButtonPanel.add(cancelAndLogOffButton);

        upButton.setText("UP");
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });
        camNavButtonPanel.add(upButton);

        downButton.setText("DOWN");
        downButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButtonActionPerformed(evt);
            }
        });
        camNavButtonPanel.add(downButton);

        nextButton.setText("NEXT--->");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        camNavButtonPanel.add(nextButton);

        chooseAMoviePanel.add(camNavButtonPanel, java.awt.BorderLayout.SOUTH);

        displayPanel.add(chooseAMoviePanel, "card3");

        chooseTimeAndTickets.setLayout(new java.awt.BorderLayout());

        titlePanel1.setBackground(new java.awt.Color(102, 255, 102));
        titlePanel1.setPreferredSize(new java.awt.Dimension(399, 75));
        titlePanel1.setRequestFocusEnabled(false);
        titlePanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        chooseAmovieLabel1.setText("choose a movie");
        titlePanel1.add(chooseAmovieLabel1);

        chooseTimeAndTickets.add(titlePanel1, java.awt.BorderLayout.NORTH);

        chooseTTdisplayPanel.setLayout(new java.awt.CardLayout());

        selectedMoviePanel.setLayout(new java.awt.CardLayout());
        chooseTTdisplayPanel.add(selectedMoviePanel, "card2");

        chooseTimeAnd3DPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout twoDor3DPanelLayout = new javax.swing.GroupLayout(twoDor3DPanel);
        twoDor3DPanel.setLayout(twoDor3DPanelLayout);
        twoDor3DPanelLayout.setHorizontalGroup(
            twoDor3DPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2016, Short.MAX_VALUE)
        );
        twoDor3DPanelLayout.setVerticalGroup(
            twoDor3DPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        chooseTimeAnd3DPanel.add(twoDor3DPanel, java.awt.BorderLayout.NORTH);

        timeDisplayPanel.setLayout(new java.awt.CardLayout());
        chooseTimeAnd3DPanel.add(timeDisplayPanel, java.awt.BorderLayout.CENTER);

        chooseTTdisplayPanel.add(chooseTimeAnd3DPanel, "card3");

        javax.swing.GroupLayout chooseTicketQtyLayout = new javax.swing.GroupLayout(chooseTicketQty);
        chooseTicketQty.setLayout(chooseTicketQtyLayout);
        chooseTicketQtyLayout.setHorizontalGroup(
            chooseTicketQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2016, Short.MAX_VALUE)
        );
        chooseTicketQtyLayout.setVerticalGroup(
            chooseTicketQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );

        chooseTTdisplayPanel.add(chooseTicketQty, "card4");

        chooseTimeAndTickets.add(chooseTTdisplayPanel, java.awt.BorderLayout.CENTER);

        camNavButtonPanel2.setPreferredSize(new java.awt.Dimension(399, 100));
        camNavButtonPanel2.setRequestFocusEnabled(false);
        camNavButtonPanel2.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        upDownButtonsPanel4.setPreferredSize(new java.awt.Dimension(133, 50));
        upDownButtonsPanel4.setLayout(new java.awt.GridLayout(1, 2));

        card1Button3.setText("UP");
        card1Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card1Button3ActionPerformed(evt);
            }
        });
        upDownButtonsPanel4.add(card1Button3);

        card2Button3.setText("DOWN");
        card2Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card2Button3ActionPerformed(evt);
            }
        });
        upDownButtonsPanel4.add(card2Button3);

        camNavButtonPanel2.add(upDownButtonsPanel4);

        upDownButtonsPanel5.setPreferredSize(new java.awt.Dimension(133, 50));
        upDownButtonsPanel5.setLayout(new java.awt.GridLayout(1, 2));

        spaceHolder2.setText("Space Holder");
        spaceHolder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaceHolder2ActionPerformed(evt);
            }
        });
        upDownButtonsPanel5.add(spaceHolder2);

        cancelAndLogOffButton2.setText("CANCEL&LOG OUT");
        cancelAndLogOffButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAndLogOffButton2ActionPerformed(evt);
            }
        });
        upDownButtonsPanel5.add(cancelAndLogOffButton2);

        camNavButtonPanel2.add(upDownButtonsPanel5);

        cancelNextButtonsPanel2.setPreferredSize(new java.awt.Dimension(133, 50));
        cancelNextButtonsPanel2.setLayout(new java.awt.GridLayout(1, 2));

        goBackButton2.setText("<---GO BACK");
        goBackButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButton2ActionPerformed(evt);
            }
        });
        cancelNextButtonsPanel2.add(goBackButton2);

        nextButton2.setText("NEXT--->");
        nextButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButton2ActionPerformed(evt);
            }
        });
        cancelNextButtonsPanel2.add(nextButton2);

        camNavButtonPanel2.add(cancelNextButtonsPanel2);

        chooseTimeAndTickets.add(camNavButtonPanel2, java.awt.BorderLayout.SOUTH);

        displayPanel.add(chooseTimeAndTickets, "second");

        chooseSeatsAndCompleteOrder.setLayout(new java.awt.BorderLayout());

        titlePanel2.setBackground(new java.awt.Color(102, 255, 102));
        titlePanel2.setPreferredSize(new java.awt.Dimension(399, 75));
        titlePanel2.setRequestFocusEnabled(false);
        titlePanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        chooseAmovieLabel2.setText("choose a movie");
        titlePanel2.add(chooseAmovieLabel2);

        chooseSeatsAndCompleteOrder.add(titlePanel2, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout chooseSeatsLayout = new javax.swing.GroupLayout(chooseSeats);
        chooseSeats.setLayout(chooseSeatsLayout);
        chooseSeatsLayout.setHorizontalGroup(
            chooseSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1916, Short.MAX_VALUE)
        );
        chooseSeatsLayout.setVerticalGroup(
            chooseSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );

        csacoDisplayPanel.add(chooseSeats);

        javax.swing.GroupLayout transactionDetailsPanelLayout = new javax.swing.GroupLayout(transactionDetailsPanel);
        transactionDetailsPanel.setLayout(transactionDetailsPanelLayout);
        transactionDetailsPanelLayout.setHorizontalGroup(
            transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        transactionDetailsPanelLayout.setVerticalGroup(
            transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );

        csacoDisplayPanel.add(transactionDetailsPanel);

        chooseSeatsAndCompleteOrder.add(csacoDisplayPanel, java.awt.BorderLayout.LINE_START);

        csacoNavButtonPanel1.setPreferredSize(new java.awt.Dimension(399, 100));
        csacoNavButtonPanel1.setRequestFocusEnabled(false);
        csacoNavButtonPanel1.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        upDownButtonsPanel2.setPreferredSize(new java.awt.Dimension(133, 50));
        upDownButtonsPanel2.setLayout(new java.awt.GridLayout(1, 2));

        card1Button2.setText("UP");
        card1Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card1Button2ActionPerformed(evt);
            }
        });
        upDownButtonsPanel2.add(card1Button2);

        card2Button2.setText("DOWN");
        card2Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card2Button2ActionPerformed(evt);
            }
        });
        upDownButtonsPanel2.add(card2Button2);

        csacoNavButtonPanel1.add(upDownButtonsPanel2);

        upDownButtonsPanel3.setPreferredSize(new java.awt.Dimension(133, 50));
        upDownButtonsPanel3.setLayout(new java.awt.GridLayout(1, 2));

        spaceHolder1.setText("Space Holder");
        spaceHolder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaceHolder1ActionPerformed(evt);
            }
        });
        upDownButtonsPanel3.add(spaceHolder1);

        cancelAndLogOffButton1.setText("CANCEL&LOG OUT");
        cancelAndLogOffButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAndLogOffButton1ActionPerformed(evt);
            }
        });
        upDownButtonsPanel3.add(cancelAndLogOffButton1);

        csacoNavButtonPanel1.add(upDownButtonsPanel3);

        cancelNextButtonsPanel1.setPreferredSize(new java.awt.Dimension(133, 50));
        cancelNextButtonsPanel1.setLayout(new java.awt.GridLayout(1, 2));

        goBackButton1.setText("<---GO BACK");
        goBackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButton1ActionPerformed(evt);
            }
        });
        cancelNextButtonsPanel1.add(goBackButton1);

        nextButton1.setText("NEXT--->");
        nextButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButton1ActionPerformed(evt);
            }
        });
        cancelNextButtonsPanel1.add(nextButton1);

        csacoNavButtonPanel1.add(cancelNextButtonsPanel1);

        chooseSeatsAndCompleteOrder.add(csacoNavButtonPanel1, java.awt.BorderLayout.SOUTH);

        displayPanel.add(chooseSeatsAndCompleteOrder, "card4");

        getContentPane().add(displayPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) moviesDisplayPanel.getLayout();
        card.next(moviesDisplayPanel);
        //card.show(moviesPanel, "card2");
    }//GEN-LAST:event_nextButtonActionPerformed

    private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upButtonActionPerformed

    private void downButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downButtonActionPerformed

    private void cancelAndLogOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAndLogOffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelAndLogOffButtonActionPerformed

    private void card1Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card1Button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_card1Button2ActionPerformed

    private void card2Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card2Button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_card2Button2ActionPerformed

    private void spaceHolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaceHolder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spaceHolder1ActionPerformed

    private void cancelAndLogOffButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAndLogOffButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelAndLogOffButton1ActionPerformed

    private void goBackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goBackButton1ActionPerformed

    private void nextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextButton1ActionPerformed

    private void card1Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card1Button3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_card1Button3ActionPerformed

    private void card2Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card2Button3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_card2Button3ActionPerformed

    private void spaceHolder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaceHolder2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spaceHolder2ActionPerformed

    private void cancelAndLogOffButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAndLogOffButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelAndLogOffButton2ActionPerformed

    private void goBackButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goBackButton2ActionPerformed

    private void nextButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new MainFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel camNavButtonPanel;
    private javax.swing.JPanel camNavButtonPanel2;
    private javax.swing.JButton cancelAndLogOffButton;
    private javax.swing.JButton cancelAndLogOffButton1;
    private javax.swing.JButton cancelAndLogOffButton2;
    private javax.swing.JPanel cancelNextButtonsPanel1;
    private javax.swing.JPanel cancelNextButtonsPanel2;
    private javax.swing.JButton card1Button2;
    private javax.swing.JButton card1Button3;
    private javax.swing.JButton card2Button2;
    private javax.swing.JButton card2Button3;
    private CardLayoutDemo.FirstPanel chooseAMoviePanel;
    private javax.swing.JLabel chooseAmovieLabel;
    private javax.swing.JLabel chooseAmovieLabel1;
    private javax.swing.JLabel chooseAmovieLabel2;
    private javax.swing.JPanel chooseSeats;
    private javax.swing.JPanel chooseSeatsAndCompleteOrder;
    private javax.swing.JPanel chooseTTdisplayPanel;
    private javax.swing.JPanel chooseTicketQty;
    private javax.swing.JPanel chooseTimeAnd3DPanel;
    private CardLayoutDemo.SecondPanel chooseTimeAndTickets;
    private javax.swing.JPanel csacoDisplayPanel;
    private javax.swing.JPanel csacoNavButtonPanel1;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton downButton;
    private javax.swing.JButton goBackButton1;
    private javax.swing.JButton goBackButton2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JPanel moviesDisplayPanel;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton nextButton1;
    private javax.swing.JButton nextButton2;
    private javax.swing.JPanel row1Movies;
    private javax.swing.JPanel row2Movies;
    private javax.swing.JPanel row3Movies;
    private javax.swing.JPanel row4Movies;
    private javax.swing.JPanel row5Movies;
    private javax.swing.JPanel selectedMoviePanel;
    private javax.swing.JButton spaceHolder1;
    private javax.swing.JButton spaceHolder2;
    private javax.swing.JPanel timeDisplayPanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel titlePanel1;
    private javax.swing.JPanel titlePanel2;
    private javax.swing.JPanel transactionDetailsPanel;
    private javax.swing.JPanel twoDor3DPanel;
    private javax.swing.JButton upButton;
    private javax.swing.JPanel upDownButtonsPanel2;
    private javax.swing.JPanel upDownButtonsPanel3;
    private javax.swing.JPanel upDownButtonsPanel4;
    private javax.swing.JPanel upDownButtonsPanel5;
    // End of variables declaration//GEN-END:variables
}
